### ISSUE TITLE
After updating Hassio OS to 9 it stop working after some minutes

### ISSUE THREAD

**Issue by synack666** [ksheumaker/homeassistant-apsystems_ecur#108]
First ECU caching ist activated, then ECU is lost, restart HA and the same, try several times. With OS before it works a lot of month.

**Comment by synack666** [comment]
ups, ECU-B and YC600

**Comment by HAEdwin** [comment]
Have you allready powercycled the ECU (turn off and on)?

**Comment by synack666** [comment]
Hi, not, have done ist just now.
HA Log is not much:
 Logger: custom_components.apsystems_ecur
Source: helpers/update_coordinator.py:151
Integration: APSystems PV solar ECU (documentation)
First occurred: 17:22:19 (1 occurrences)
Last logged: 17:22:19
Error fetching apsystems_ecur data: Error using cached data more than 5 times. See log, and try power cycling the ECU.

Version 1.2.16

**Comment by synack666** [comment]
Just went back to 8.5, some minutes after powercycle it happens again, will see what is with 8.5 again to make sure that depends to HA and not something other.

**Comment by synack666** [comment]
With 8.5 no more problems, everything was fine so i could say OS 9 was the problem.

**Comment by HAEdwin** [comment]
No problem here. (ECU-R, QS1 + YC600)
![image](https://user-images.githubusercontent.com/82239374/190667522-448fc076-695e-4f6d-abfe-ec89bff0268a.png)
Fails the integration immediately after the home-assistant reboot? Differences are IP6 support and socket receive and send buffer size which I could very possibly relate to the problem.

**Comment by synack666** [comment]
No, it tooks some minutes, first caching activatet and some minutes later all sensors lost, ECU offline. App on handy works at same time.

**Comment by HAEdwin** [comment]
What about changing the value to 1024 on line 34 of APSystemsSocket.py (self.recv_size = 1024) ? Are you using a Raspberry Pi (which model)?

**Comment by synack666** [comment]
Will test this next week, i use a Intel Nuc.

**Comment by HAEdwin** [comment]
See if others with an intel NUC also have problems with the new OS 9 release. There are few to no options in the integration to fix this unless you come up with ideas. Troubleshooting takes a lot of time if you don't have the hardware yourself unfortunately.

**Comment by synack666** [comment]
Morning :-)

Test results:

It works since 2h
First i changed the value in 8.5 -> works
then upgrade to 9.0, reboot
No caching in log and no faults!

Thanks a lot, this integration is much important for me.
Problems with NUC and 9.0 i found are mostly with USB sticks and driver things.

I close here and wish a pleasant week
