### ISSUE TITLE
ECU-R shows entire lifetime energy consumed during one hour in the energy

### ISSUE THREAD

**Issue by arduinopjotr** [ksheumaker/homeassistant-apsystems_ecur#126]
I have the same issue her as mackowskim since a couple of days. I did an upgrade of the ecu-r plugin. After the upgrade it looks like the ECU plugin sometimes write a zero in the entity "sensor.ecu_lifetime_energy" . If the next data is correct again (e.g. 400kWh) Then the statistics will giva a value of 400 because of the delta from 400-0 = 400.
Is it possible that the ECU-R plugin writes a zero when there is no connection to the gateway ? Is it a plan to block the updates of the entity "sensor.ecu_lifetime_energy" if the value is zero.
PS The entity sensor.ecu_today_energy" does nog have any gliches.

![glitch](https://user-images.githubusercontent.com/35777674/196794538-62e8bc20-3bc6-4962-b1f9-f8832943b60d.JPG)

**Comment by HAEdwin** [comment]
In version 1.2.19 I removed the check because out-of-the-box ECU's do have zero lifetime energy. I will reintroduce the check and figure out a way around that for freshly connected ECU's. The zero values are under some circumstances received from the ECU they are not produced by the intergration.

**Comment by arduinopjotr** [comment]
Thanks for your reply and your hard work !!

**Comment by HAEdwin** [comment]
Released v1.2.23 where I re-introduced the check on zero values for life-time energy.
