### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by duckietm** [ksheumaker/homeassistant-apsystems_ecur#127]
Phyton3 is cause high CPU usage after the last update, i fixed it with the latest update from : https://github.com/HAEdwin/homeassistant-apsystems_ecur/commits/main

- Update config_flow.py
- Update __init__.py
- Update const.py

After those update CPU is back to 0.2% instead of 45%

**Comment by HAEdwin** [comment]
@duckietm Do you still have high CPU usage on the later versions 1.2.23 ?

**Comment by HAEdwin** [comment]
I will close this issue, if another issue arises, feel free to create a new issue.
