### ISSUE TITLE
Support for DS3D-L inverter

### ISSUE THREAD

**Issue by dclobato** [ksheumaker/homeassistant-apsystems_ecur#135]
Today, I added 4 more panels to my setup. Now, I have 4 micro inverters generating 8.64kWp

![Web capture_14-11-2022_175844_10 0 1 245](https://user-images.githubusercontent.com/4229987/201764680-08d0b528-8d50-4db5-ac38-ea0b94370b2e.jpeg)

I had 3 QS1 microinverters, and they have all details on the integration

![Web capture_14-11-2022_175715_10 0 1 245](https://user-images.githubusercontent.com/4229987/201764514-48bd7a5d-11ea-490e-8bed-7f73d2c01f6a.jpeg)

The new inverter has no details at all...

![Web capture_14-11-2022_175741_10 0 1 245](https://user-images.githubusercontent.com/4229987/201764579-a4998802-1b42-4648-9330-84badcfba83e.jpeg)

The new inverter is a [**DS3D-L**](https://latam.apsystems.com/wp-content/uploads/2021/11/4303601202_APsystems-Microinverter-DS3D-For-Brazil-Datasheet_-Rev1.0_2021-11-19.pdf).

I saw, on the code, that there is support for DS3 inverters. Is it possible to add support for the DS3D model?  What information should I collect/provide to allow this new model be added to the integration?

**Comment by HAEdwin** [comment]
Have you tried uninstalling the integration (Settings>Devices & Services>Integrations and then using the menu to delete the integration) restart HA and add the integration again. The entities might than get added/discovered.

**Comment by dclobato** [comment]
> Have you tried uninstalling the integration (Settings>Devices & Services>Integrations and then using the menu to delete the integration) restart HA and add the integration again.

I understand that the integration detected the new entity.

I believe that the problem lies on the fact that the DS3D-L inverter has a different code. From the [code](https://github.com/ksheumaker/homeassistant-apsystems_ecur/blob/acbfe25b9329f92e1d3d98cfc13545cb1db23cc7/custom_components/apsystems_ecur/APSystemsSocket.py#L324), each inverter has a different code: 01 for YC600/DS3, 02 for YC1000 and 03 for QS1. Maybe the DS3D-L has a different code on the response string...

**Comment by HAEdwin** [comment]
Yes, that's a good starting point if entities from the inverter are not discovered. You can uncomment line 262 by removing the first # . In /config/home-assistant.log you will find the results from the inverter query. Can you share that string for further analysis?

**Comment by dclobato** [comment]
Here it is

```
2022-11-15 17:33:17.001 WARNING (SyncWorker_1) [custom_components.apsystems_ecur.APSystemsSocket] b'415053313130313139303030323030303100042022111517284180400004919001303302580089001800d90025002c00448040000512700130330258008d006900d9006e001d000a8040000513600130330259008d000e00da000c000d000b7060000305790130340258009500e400d7009700d7454e440a'
```

**Comment by HAEdwin** [comment]
Daniel, I've made to changes to APsystemsSocket.py to add compatibility with this new DS3D-L inverter. Before a new release could you check if this works out fine for you? Follow link for changes.
https://github.com/ksheumaker/homeassistant-apsystems_ecur/commit/bcd62f98a08fdbbc5a9d3ed1deb11fab37a035c2

**Comment by dclobato** [comment]
> Before a new release could you check if this works out fine for you?

I believed it's working now!

![Web capture_16-11-2022_15125_10 0 1 245](https://user-images.githubusercontent.com/4229987/202258078-526efcec-1a9a-45c8-8493-e9f174bc0262.jpeg)

![Web capture_16-11-2022_15151_10 0 1 245](https://user-images.githubusercontent.com/4229987/202258117-30792a85-7323-4e28-9109-2ce1015252be.jpeg)

Can I close the issue?

Thanks!

**Comment by HAEdwin** [comment]
Yes you can, glad it worked out fine. Thanks for supplying info on this relatively new inverter so that I could add it. It will be included in the new release.
