### ISSUE TITLE
Repository Add-on error

### ISSUE THREAD

**Issue by ThibautBascoulergue** [ksheumaker/homeassistant-apsystems_ecur#140]
Hello,

When i add the url of repository on my Home Assitant, i have an error below 👍 

![image](https://user-images.githubusercontent.com/42678960/204586203-70617942-017a-4a4f-96e6-c91eb1553da0.png)

I'm in release 2022.11.2

![image](https://user-images.githubusercontent.com/42678960/204586335-a3c24a84-1f40-40d6-aee2-5c3bfb31cfa7.png)

Thx for help.

**Comment by HAEdwin** [comment]
Please read this link: https://github.com/ksheumaker/homeassistant-apsystems_ecur/issues/138
Feel free to add or reopen this issue if this does not solve your problem.
