### ISSUE TITLE
Cannot connect to ECU

### ISSUE THREAD

**Issue by HAEdwin** [ksheumaker/homeassistant-apsystems_ecur#141]
@HAEdwin 
No good... and didn't expect it to work as an earlier performed Portscan did not show port 8899 open:

![image](https://user-images.githubusercontent.com/67055019/204595729-3bf36922-99f6-49eb-b5b0-53ed5e38ae90.png)

_Originally posted by @Verguldebarman in https://github.com/ksheumaker/homeassistant-apsystems_ecur/issues/139#issuecomment-1330990216_

**Comment by HAEdwin** [comment]
Are you sure this is the ECU and not another node? Did you assign a fixed IP-Address to the ECU or might if have gotten another IP-Address from the DHCP server (lease expired)?

**Comment by Verguldebarman** [comment]
Proof that the address is correct.

From my router:
![image](https://user-images.githubusercontent.com/67055019/204612451-587ccbd1-7a3a-4fc3-aee1-a25113d31e3a.png)

And if you lookup the MAC address:
![image](https://user-images.githubusercontent.com/67055019/204612712-a0bbd5cb-8f0b-47b3-9be3-4ba1b1726da4.png)

I did not assign a fixed IP, but reserved it in my Router's DHCP list:
![image](https://user-images.githubusercontent.com/67055019/204613129-08ee0b3e-e7cc-4ee0-b479-ebcfd72a6d7f.png)

so... I'm pretty sure that correct.

**Comment by HAEdwin** [comment]
Are the ECU and HA node on the same network (subnet. VLAN). Is the ECU ethernet connected or wireless? Try the other method and see if you get responses using packet sender. Do not use the ECU's temporary hotspot used in the configuration step.

**Comment by Verguldebarman** [comment]
> Are the ECU and HA node on the same network (subnet. VLAN). 

yes

> Is the ECU ethernet connected or wireless? 

LAN

> Try the other method and see if you get responses using packet sender. Do not use the ECU's temporary hotspot used in the configuration step.

Just tried getting the ECU-R WLAN connected but can't seem to get that working. Tried twice, but somehow the ECU will not connect with my wifi (and I know for sure I did not make a typo). Looks like more strange things happen in my ECU :-( 

Does anyone know if it is possible to reset my ECU? And if so; will my roof/solar setup be remembered, or will that also reset everything. Meaning I will have to ask the solar-installation-guys to return and fix things.....

**Comment by Verguldebarman** [comment]
SOLVED !!!!

I found the solution:

         You must disconnect the ethernet cable. Otherwise, WIFI will not be used.

Connect HA to ECU-R via wifi and now it works!

Thanks @HAEdwin

**Comment by HAEdwin** [comment]
Great! But OMG I overlooked your line "My brand new ECU-R (2160xxxxx from October 2022)". The connection table in the readme shows the older ECU-R (without sunspec logo on the back) only works wireless.  Anyway, great that it is solved now. I'll close this issue. Might any other issue arrise, feel free to open a new one.

**Comment by Verguldebarman** [comment]
Yeah, knew that... but didn't know that LAN cable must not be connected in order to have WIFI enabled.  Anyway, great it is solved!

**Comment by HAEdwin** [comment]
Ok, maybe that changed from older firmware versions because I remember I had the ECU connected both ways. I'll add it to the documentation. Thanks!
