### ISSUE TITLE
Can't find ECU a this IP-Adress

### ISSUE THREAD

**Issue by ThibautBascoulergue** [ksheumaker/homeassistant-apsystems_ecur#151]
Hello, 

I try to add my ECU-R in Home-Assistant but, i have an error when i put ip address, integration return an error "Can't find ECU at this IP-AdDress.

I have check ip with this command, so i think its good.
![image](https://user-images.githubusercontent.com/42678960/216276382-58b8e7da-1933-46b6-bc1f-40b8f6369236.png)

And, in the log file i have this. You think its because i have no production ?
![image](https://user-images.githubusercontent.com/42678960/216276200-b064e79e-4f1d-414c-85ed-915784f61b3c.png)

thank's.

**Comment by HAEdwin** [comment]
Yes, probably because the life-time energy on the ECU is still at zero. Look at this issue to solve this: https://github.com/ksheumaker/homeassistant-apsystems_ecur/issues/113
