### ISSUE TITLE
Is the QT2 supported?

### ISSUE THREAD

**Issue by TheRedBull205** [ksheumaker/homeassistant-apsystems_ecur#159]
I am currently looking into solar panels in combination with a microinverter. But this also needs to work with Home Assistant.

Is the new QT2 also supported by this project in combination with the ECU-R?
https://emea.apsystems.com/nl/portfolio-item/apsystems-qt2/

**Comment by HAEdwin** [comment]
It might but I cannot guarantee it. We've seen other inverter models being added to this integration, these needed adoption in the code and so after a while the integration was made more generic to suit more models automatically.

**Comment by Slamkryp** [comment]
Yes, i can confirm qt2 is working. just type in the ecu-r ip and wifi password and its ready to go!  (only tested with 1 qt2)

**Comment by HAEdwin** [comment]
Thanx for confirmation @Slamkryp
