### ISSUE TITLE
Long term statistics for inverter sensors

### ISSUE THREAD

**Issue by mcflexus** [ksheumaker/homeassistant-apsystems_ecur#164]
I see the ecu sensors have long term statistics enabled but the inverter sensors don't. Can you enable them? I think especially for temperature sensor it makes much sense to do so. Thank you for this great integration!

**Comment by HAEdwin** [comment]
They are long term (at least when I quick tested it)
![image](https://user-images.githubusercontent.com/82239374/227632872-b3b6325a-202f-4b7f-951a-28055702900b.png)

**Comment by mcflexus** [comment]
I mean something else, this is just the history of a few days, long term statistics are stored for ever. See https://data.home-assistant.io/docs/statistics/

**Comment by HAEdwin** [comment]
I see what you mean, state_class is missing. Are you able to add that to the integration?

**Comment by mcflexus** [comment]
Don't think that should be a problem. I'll try to find some time this weekend.

**Comment by mcflexus** [comment]
just made a pull request, tested locally and working as expected.

**Comment by HAEdwin** [comment]
Merged the pull request, thank you!

**Comment by mcflexus** [comment]
No problem!
