### ISSUE TITLE
VOLT -> ELECTRIC_POTENTIAL_VOLT

### ISSUE THREAD

**Issue by EntonoX** [ksheumaker/homeassistant-apsystems_ecur#17]
With the latest HomeAssistant update the integrations stops running. In the logs are errors mentioning the VOLT import could not be found. 

After manually changing VOLT -> ELECTRIC_POTENTIAL_VOLT on line 30 and 67 in sensor.py things are working again.

**Comment by ksheumaker** [comment]
Fixed in v1.0.3
