### ISSUE TITLE
negative energy

### ISSUE THREAD

**Issue by wallb35** [ksheumaker/homeassistant-apsystems_ecur#174]
Hello,
last two days 5 and 6 April 2023, I've got past day energy produced as a negative value in Energy Dashboard using ECU today Energy as Solar Production sensor (see two screenshots). Was working for month before.
Between 2 and 3 am in Dashboard energy, probably when the sensor reset in my ECU-B, all previous production from passed day come as negative value.
no problem with ECU total energy but with less precision.
looks like the sensor have the good value (see attached file).
I reboot my ECU-B today. Need to wait for tomorrow to see if it solved my issue.
ECU-B 1.2.26
ECU Integration 1.2.28
Home assistant container 2023.3.0
Regards.
Yannig
<img width="690" alt="Capture d’écran 2023-04-06 à 10 38 40" src="https://user-images.githubusercontent.com/92517256/230322770-8fedd7fe-354e-4053-a487-3ff456431ccf.png">
<img width="707" alt="Capture d’écran 2023-04-06 à 10 38 57" src="https://user-images.githubusercontent.com/92517256/230322795-c6f0442a-b2b9-471c-8291-2fcfd3ccfe67.png">
![ecu today energy](https://user-images.githubusercontent.com/92517256/230323581-4cc2ee72-e02b-48ba-b359-cf0cee085825.png)

**Comment by Doudou14** [comment]
I have the same problem, so I use "sensor.ecu_lifetime_energy". But I don't see less precision.

**Comment by HayaminiNL** [comment]
I am experiencing the same thing with the integration:
![image](https://user-images.githubusercontent.com/107961050/230370475-33086025-a6a0-4a1c-81c2-aa5a2c44c744.png)

It gives the negative number of the amount of kW of the previous day.

**Comment by wallb35** [comment]
> I have the same problem, so I use "sensor.ecu_lifetime_energy". But I don't see less precision.

lifetime energy is one digit precision vs today 2 digit precision.

**Comment by HayaminiNL** [comment]
Just my 2 cents on the code change 3 days ago.

The 'sensor' that stores the value is using another value as its input:
![image](https://user-images.githubusercontent.com/107961050/230398162-b15156d1-de96-45a4-baac-d57be76f8024.png)

It is changed to: "stateclass=SensorStateClass.TOTAL" from "stateclass=SensorStateClass.TOTAL_INCREASING".

Before the change both sensors use the TOTAL_INCREASING.
Maybe this got mixed up, so that today_energy should use TOTAL_INCREASING and lifetime only TOTAL?

Does it make sense when I thing that it caused the 'total' going negative when being reset to zero at the new start of the day-measurement?

**Comment by renini** [comment]
Experienced exactly the same.

**Comment by ViperRNMC** [comment]
Same issue here, started from 5april

**Comment by HayaminiNL** [comment]
Swapping the variables fixed the issue on my side.

When you connect via Terminal to the HASS node, you can edit the PY file to make it work for now.

**Comment by wallb35** [comment]
> Swapping the variables fixed the issue on my side.
> 
> When you connect via Terminal to the HASS node, you can edit the PY file to make it work for now.

Thank you, modification done. Waiting for result tomorrow morning ;)

**Comment by HayaminiNL** [comment]
Well done for this quick merge!

@wallb35, did the code change result in 'normal operation for you too?

**Comment by wallb35** [comment]
I forgot to restart home assistant :/ so no change yet. Hope this will be good tomorrow.

**Comment by wallb35** [comment]
Latest version solved the problem. Fixed

**Comment by wallb35** [comment]
Latest version solved the problem. Fixed

**Comment by Eraser127** [comment]
Same problem here with ECU-R, so just need to edit that sensor.py? Or will there be a automatic update?

**Comment by HAEdwin** [comment]
I guess this is fixed so I'll close the issue. Feel free to open a new issue if needed.
