### ISSUE TITLE
keep getting error message

### ISSUE THREAD

**Issue by X0Topix0X** [ksheumaker/homeassistant-apsystems_ecur#184]
cant figure this out i have tryed every think but keeps getting this same error. i set ecu to wifi, tryed got the ip placed it in even tryed the 2160xxxxx code but notting seems to work. the Ecu is a ECU-R-Eu

wat am i doing worng

![image](https://user-images.githubusercontent.com/132162882/235366018-705dfa25-adc7-4798-93fd-624b2b9480d5.png)

**Comment by X0Topix0X** [comment]
NVM i am stuppid, was running HA on different router(network)

**Comment by HAEdwin** [comment]
Happens more often, no problem. I will close this issue. Feel free to open a new issue if needed.
