### ISSUE TITLE
Feature request : inverter DC voltage in V of each channel

### ISSUE THREAD

**Issue by lesissou** [ksheumaker/homeassistant-apsystems_ecur#194]
Hi 
good job and thanks for sharing
Is it possible to add the sensor.inverter_[UID]_DC_voltagech_[1-4] - the DC voltage in V of each channel (model depentent) of the inverter ?

Thanks a lot

**Comment by wasn-eu** [comment]
that would be great if beside the DC voltage the dc_current could be read

**Comment by wasn-eu** [comment]
You can find the APSystems ECU Protocol - Command Group 11 in the Appendix section on https://github.com/npeter/ioBroker.apsystems-ecu

**Comment by k-plan** [comment]
Hi,

yes, it will be a great feature to see inverter DC voltage in V and DC  current in A on each channel.
Thanks in advance for helping with this feature request.

cu
k-plan

**Comment by HAEdwin** [comment]
@lesissou I'm pretty sure that DC voltage and current are not part of the data obtained from this query method. If you can point me specifically to the part where DC voltage can be drawn from the data please let me know, I may have missed it. What I do know is that DC voltage and current per panel is sent to the EMA website, but that does not include the signal strength (as far as I have been able to find out), but that's a whole different story. I can't really add this feature with this integration. I you agree we can close this feature request.

**Comment by lesissou** [comment]
It is right, you can see this values on the APSystem Power Control Software : https://<IP ECU>/index.php/configuration
I thinked this values should be include in the data, but if you say NO that fine.
Thanks you a lot to try it
Thanks you for your job, since the last version I haven't any issue for the history value
Regards

**Comment by HAEdwin** [comment]
I totally agree that these DC values on panels would provide additional info and should be included but unfortunately the received data after querying the ECU with the specific method from within this integration does not contain the Direct Current data. It only contains the Alternating Currents. I know that the ECU's have the data but there has not been further more efforts to reverse engineer and look for a query to retreive these values as well.
