### ISSUE TITLE
Wrong timezone

### ISSUE THREAD

**Issue by carpaccioMedia** [ksheumaker/homeassistant-apsystems_ecur#196]
Hello,

the integration is working in my home assistant instance.
the only problem i can't find where to change the timezone. 
i'm living in the netherlands but the timezone is gmt-8. the sensor is resetting to early to 0 for the daily power.
on the webinterface off apsystems is the time zone the right one, my home assistant is also on the good timezone.

many thanks

**Comment by HAEdwin** [comment]
As far as I tried to solve this, this is unfortunately a bug in the ECU's firmware. Whatever setting you might try: factory or ETC GMT+2, the ECU will output Etc/GMT-8 when you query it.  The System Time shown on the APSystems EMA site uses another way to resolve the time. Best is to ignore the retreived timezone data for now. For the daily energy reset, I'm not sure what the rule for the daily reset is. The value is being retreived only and not being manipulated by the integration. It's weird though that the reset seems to differ somehow. I'm also in The Netherlands and my daily reset today was at 6 in the morning.
