### ISSUE TITLE
netcat ok, but still no connection to ECU

### ISSUE THREAD

**Issue by backupandforkacc** [ksheumaker/homeassistant-apsystems_ecur#198]
![grafik](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/1709199/f9ad6d82-70b9-461a-9e45-b33b35b19a0e)

```
/config# nc -v 192.168.103.68 8899
192.168.103.68 (192.168.103.68:8899) open
APS1100160001END
APS110095000121630009028301Y������� 

```
![grafik](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/1709199/81d6c064-73e3-4076-ab1b-959994277e94)

I had to make a screenshot as I cannot copy the last line completely.

I measure the power production by an energy plug and it shows > 100 W.

**Comment by sbemmann** [comment]
I have the same problem here

**Comment by HAEdwin** [comment]
If it is a new installation (ECU is new), the life-time energy is still zero. Then you have two options: Wait until life-time energy is no longer zero or edit APSystemsSocket.py and place a # before lines 116 to 119. In previous versions the issue was here: https://github.com/ksheumaker /homeassistant-apsystems_ecur/issues/113#issuecomment-1263436330

**Comment by HAEdwin** [comment]
@backupandforkacc  and @sbemmann Please provide feedback on this issue, can it be closed?

**Comment by giagrand74** [comment]
Hi, same problem on my setup, Was all ok than ECU disconnected with same error message.
May I ask how to perform the change suggested  on #113?
Can I do it via the web interface or do I login via ssh etc? Thanks in advance for your support.

**Comment by HAEdwin** [comment]
You can use "File Editor" it's an add-on for Home Assistant. Browse to APSystemsSocket.py and comment out the lines with a # 
Then save the file and restart HA.

**Comment by giagrand74** [comment]
I did as per below but same problem:

def query_ecu(self):
        self.open_socket()
        cmd = self.ecu_query
        self.ecu_raw_data = self.send_read_from_socket(cmd)
        self.close_socket()
        try:
            self.process_ecu_data()
            # conflicting interests of which 113 is just a temorary issue and less common
            # https://github.com/ksheumaker/homeassistant-apsystems_ecur/issues/126
            # https://github.com/ksheumaker/homeassistant-apsystems_ecur/issues/113
            # if self.lifetime_energy == 0:
            #    error = f"ECU returned 0 for lifetime energy, this is either a glitch from the ECU or a brand new installed ECU. Raw Data={self.ecu_raw_data}"
            #    self.add_error(error)
            #    raise APSystemsInvalidData(error)
        except Exception as err:
            raise APSystemsInvalidData(err)
        
        # Some ECUs likes the socket to be closed and re-opened between commands
        self.open_socket()

**Comment by giagrand74** [comment]
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148276976/5809815d-c7e9-4685-8704-3fe446298abf)

**Comment by giagrand74** [comment]
Did i make something wrong?

**Comment by giagrand74** [comment]
ECU version
ECU-B-EU Article No. 211018

Home Assistant 2023.10.5
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231005.0 - latest

APSystems ECU-R v1.2.30

Device seems working correctly on apsystem website:
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148276976/55cf9bd0-42ac-4357-b4d0-0b29c97b870b)

Via ssh it replies to ping but no result from the nc query....  :-/ neither a error message.

![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148276976/de00930f-f998-4d03-91a5-172ca5331b74)

**Comment by giagrand74** [comment]
It's strange, i removed the wifi antenna from the ECU, still no correct reply from ssh but now it works...
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148276976/4bd24974-94d6-483d-ba9b-a896bf3dbedc)
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148276976/90f38404-5467-4353-a5ef-6c34ed9d72f0)
I tested changing the config from 300 to 600 sec and change is configured without any problem.

![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148276976/3336bb0c-ff5a-4d86-a469-845562b995bb)

**Comment by giagrand74** [comment]
For information, now I got the reply 
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148276976/353cb162-c7ae-4f78-a785-1c0cad3ec994)

**Comment by HAEdwin** [comment]
You removed the WiFi antenna and all is working now? What do you mean with "i removed the WiFi antenna from the ECU"?

**Comment by giagrand74** [comment]
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148276976/7750f257-0a4a-4474-b8ca-fd1bee831972)
I unscrewed the antenna as per image, I know sound crazy...now I'm running just with the zigbee antenna connected on the box, Maybe I had a faulty antenna or a faulty SMA connector. 
I'll test putting back the antenna and I let you know.

**Comment by HAEdwin** [comment]
Indeed, I recall another case where removing the antenna had an effect on the operation of the ECU. I really can't figure out exactly how this works, is it interference from another device nearby? I have no idea, but it's nice that it seems to work now.

**Comment by HAEdwin** [comment]
I'll close this issue, feel free to create a new issue if you have any questions
