### ISSUE TITLE
Home Assistant 2021.9.1 energy dashboard broken

### ISSUE THREAD

**Issue by royvanmanen** [ksheumaker/homeassistant-apsystems_ecur#21]
in sensor.py please change following:

line 16-18 original:
from homeassistant.components.sensor import (
    STATE_CLASS_MEASUREMENT,
 )
line 16-19 modified:
from homeassistant.components.sensor import (
    STATE_CLASS_MEASUREMENT,
    STATE_CLASS_TOTAL_INCREASING
)

after modification this is line 60:
devclass=DEVICE_CLASS_ENERGY, icon=SOLAR_ICON, stateclass=STATE_CLASS_MEASUREMENT),
change this to:
devclass=DEVICE_CLASS_ENERGY, icon=SOLAR_ICON, stateclass=STATE_CLASS_TOTAL_INCREASING),

**Comment by Levdbas** [comment]
I can confirm this fixes the energy dashboard. Great work @royvanmanen

**Comment by HAEdwin** [comment]
@royvanmanen This issue should be solved and can be closed, correct?

**Comment by royvanmanen** [comment]
jazeker, bedankt!

**Comment by HAEdwin** [comment]
Jij ook bedankt!
