### ISSUE TITLE
When inverters are off, inverter sensors entities should not update

### ISSUE THREAD

**Issue by wildekek** [ksheumaker/homeassistant-apsystems_ecur#214]
When the inverters are off, the following sensors report a value of 0:
- sensor.inverter_xxxxxxx_power_ch_1
- sensor.inverter_xxxxxxx_power_ch_2
- sensor.inverter_xxxxxxx_frequency
- sensor.inverter_xxxxxxx_voltage

The following sensors report their last know state:
- sensor.inverter_xxxxxxx_signal

The correct behavior is not updating the state, like the temperature sensor:
- sensor.inverter_xxxxxxx_temperature

Wrong:
<img width="502" alt="image" src="https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/2332647/6524211e-841f-46ff-b9b0-2309b458dcc5">

Expected behavior:
<img width="500" alt="image" src="https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/2332647/8c73f68b-9088-4398-b2cb-31c793f360be">

**Comment by HAEdwin** [comment]
The temperature sensor(s) of the inverter(s) also reported zero when switching off the inverter(s). This zero value does not reflect the actual temperature of the inverter. That is why the preference arose not to update these graphs.

**Comment by wildekek** [comment]
Yes, that makes total sense. So you agree this behavior should apply to the other graphs as well?

**Comment by HAEdwin** [comment]
When we would do this, frequency sensor graphs would show up like a series of lines __   __   ___   ___   ___
I created a poll to see how others think about this idea: https://github.com/ksheumaker/homeassistant-apsystems_ecur/discussions/215

**Comment by HAEdwin** [comment]
I'll try to make it optional like so:
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/82239374/01f4b568-2843-43f1-837e-49fbc6f8dffb)

**Comment by wildekek** [comment]
Sweet, that we would be a great addition!

**Comment by HAEdwin** [comment]
I'm currently testing... If you would like to test, you can find the sources here: https://github.com/HAEdwin/homeassistant-apsystems_ecur. 

Personally I like to update the graphs when the inverters are offline because this morning it showed power being zero on two channels with the inverter online, showing that these parameters are indeed zero and not a guess.
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/82239374/1f57bba8-c505-4b78-8150-fad3bed95bd0)

**Comment by HAEdwin** [comment]
@wildekek ik ben klaar met testen. De v1.3.0 beta staat klaar voor installatie en testen :tada:

**Comment by HAEdwin** [comment]
@wildekek With some delay due to the busy Christmas holidays and a software bug the 1.3.0b version includes the feature - ready for further testing 🎉

**Comment by wildekek** [comment]
Nice work @HAEdwin ! I've installed it and will check out the results in 24h. Thanks a bunch and happy holidays to you.

**Comment by HAEdwin** [comment]
Fixed: Caught a bug on a fresh install; when configuring the integration it throws an error on the no_graphs because there was no default so the key and value (False) could not be created.

Release was updated just now. @wildekek, All is in working as expected?

**Comment by wildekek** [comment]
Yep, thanks for your work!
