### ISSUE TITLE
2 ecu-b together not working

### ISSUE THREAD

**Issue by patmtp35** [ksheumaker/homeassistant-apsystems_ecur#219]
strange behavior, I have two ecu-b, when I include one it works correctly, if I include the second one, it brings up the dataq and the first does not bring it up anymore... if I override the first and then re -included, it is the second which no longer reports the datas.
i have a ping on etch others et the ping it's ok

**Comment by HAEdwin** [comment]
From the readme instructions: It currently supports one ECU (one instance of the integration) but a work-around is available https://github.com/ksheumaker/homeassistant-apsystems_ecur/issues/142 Hope this works for you.

**Comment by patmtp35** [comment]
ok tanks for the prompt answer , i ll try to do this solution 
regards
