### ISSUE TITLE
Cant find ECU or  life-time energy is 0

### ISSUE THREAD

**Issue by balla1337** [ksheumaker/homeassistant-apsystems_ecur#220]
Won't work any longer i noticed today, can,t connect. Checked connection,but App/ECU all is fine and IP still correct.

**Comment by HAEdwin** [comment]
What are the results of the https://github.com/ksheumaker/homeassistant-apsystems_ecur#test-your-connection ? If that part works fine then the life-time energy must be zero for some reason. Did you install a new ECU? Have you noticed a firmware update? What type of ECU do you have? Also use the search function and read this: https://github.com/ksheumaker/homeassistant-apsystems_ecur/issues/198

**Comment by balla1337** [comment]
Thank you for fast reply man, i have ECU-B hard-reset + repeater reset recently fixed my Problem. Have a nice day

**Comment by HAEdwin** [comment]
Thanks for the feedback on your own solution to reset the ECU-B and repeater. 👍
