### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by giagrand74** [ksheumaker/homeassistant-apsystems_ecur#227]
Unable to complete the setup
Already tried to restart the ECU-B and restart HA
Device is available on the network and reply correctly to nc -v 172.168.1.56 8899
v 1.3.1

Core
2024.1.5
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148276976/7fff6bc1-fd5d-43f5-a01c-2326377aaafd)

**Comment by HAEdwin** [comment]
What if you take an older version of the integration 1.2.30 for example?

**Comment by HAEdwin** [comment]
Thanks for the feedback, there might be a bug somewhere, I'll have to look into that. Was it a complete new install?

**Comment by giagrand74** [comment]
Update to version 1.3.1
All seems ok till now.
I just downgrade to 1.2.30 and updated again today, I did not removed the integration from HACS.

**Comment by HAEdwin** [comment]
Strange, not sure what the issue was because I was not able to reproduce it. Might any other question arrise, feel free to open a new issue.
