### ISSUE TITLE
Can't add current production to energy dashboard

### ISSUE THREAD

**Issue by fdr76** [ksheumaker/homeassistant-apsystems_ecur#23]
Hello,

I can only select the total lifetime production to the energy dashboard and not the current production. Do I something wrong. I get th follow message:

<img width="434" alt="image" src="https://user-images.githubusercontent.com/72302555/132941444-4848137b-700d-4821-b378-d4a5d27fc0f6.png">

**Comment by HAEdwin** [comment]
This entity should be selectable: sensor.ecu_current_power

**Comment by fdr76** [comment]
I made a think fault.
