### ISSUE TITLE
Bug Solar Production (history?)

### ISSUE THREAD

**Issue by brunnomcosta** [ksheumaker/homeassistant-apsystems_ecur#233]
Hello everything is fine? I managed to integrate and can see the data in real time in Home Assistant. However, I'm trying to integrate with the HA solar energy session and it doesn't work. I noticed that the statistics are empty, although the entity reports the value in real time. Other device statistics are keeping history correctly. But those integrated with ApSystems are not keeping history. Can you help me?

**Comment by brunnomcosta** [comment]
[Uploading 2024-02-16 13-55-02.zip…]()

**Comment by HAEdwin** [comment]
In the Energy Dashboard it can take a while before data arrives.
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/82239374/586b5449-516f-4be7-b69a-f10feada95cc)
