### ISSUE TITLE
Energy today wrong

### ISSUE THREAD

**Issue by RackerCRO** [ksheumaker/homeassistant-apsystems_ecur#235]
I've noticed for some time now that Energy Today is higher in Home Assistant than reported on AP app or AP web site. 
For example, HA for today reports 9.5kWh production where AP app only 7.9kWh. I've checked for past 7 days and it's higher for every day. I tried rebooting my ECU but it didn't help. My ECU is R model 2160
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148647121/f38782d1-8437-4239-a067-c4a3d58a5bd0)
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148647121/7d95a081-f163-4315-9d21-07a2c42f8b0e)

Since I'm checking these values during the night and for past days this can't be delay issue I guess. 

Regards.

**Comment by HAEdwin** [comment]
Yes, you are right. When I connect directly to my ECU (2160) the ECU app shows the same value (as expected) as the integration which is currently higher than the EMA website. I don't know what's going on or what data to trust right now; the value from the ECU itself or the EMA site. Btw. Today Energy is not being send to EMA, Today Energy is calculated locally on the server. It's certainly not an integration issue, the integration is just reading the Today Energy parameter from the ECU. I'll have to spend some time to perform a parallel calculation and see which value is correct. What firmware are you running?

**Comment by RackerCRO** [comment]
My EMA app has same values as EMA website.
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148647121/960c7e5c-b275-4ab3-a6b3-0e785f690b19)

Where can I check FW version? EMA app manager?

**Comment by HAEdwin** [comment]
It's an attribute of Today Energy
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/82239374/385042ce-5e53-470e-b9b6-d79f50440e67)

The EMA app takes data from the EMA site, the ECU app or ECU manager app from the ECU.

**Comment by RackerCRO** [comment]
Fond it
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148647121/9eba0965-c9dd-4deb-9b47-ed8771dedcb1)

**Comment by HAEdwin** [comment]
Currently Today Energy matches in EMA and ECU, both 1,23kWh

**Comment by RackerCRO** [comment]
Not here :(
EMA app
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148647121/bbcf3872-e79c-4b1e-8b2f-19f2a9dafd02)

HA
![image](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/148647121/11cc2e0a-37bf-4047-8d31-37436504f959)

**Comment by HAEdwin** [comment]
Strange, can't do anything about this right now.

**Comment by HAEdwin** [comment]
@RackerCRO I'll close this issue for I can't solve this. Impact is huge thought taking all the APsystems customers worldwide. Apparently it was never the intention to follow the ECU values ​​so closely, all customers look at the EMA site. Feel free to raise a new issue if any other arrises.
