### ISSUE TITLE
Using cached data a lot

### ISSUE THREAD

**Issue by m3tc0n** [ksheumaker/homeassistant-apsystems_ecur#253]
Hi, my APsystems ECU integration is using cached data a lot. I don't think that's any good. How to solve that? It's occurring on version 1.4.1 and beta version 1.4.2.

![Screenshot_20240516-215723.png](https://github.com/ksheumaker/homeassistant-apsystems_ecur/assets/106514117/762a512a-2e97-4c68-b13a-6ee670b1c180)

Edit: my ECU is a 2160 version and on firmware ECU_R_1.3.10

**Comment by HAEdwin** [comment]
Please read earlier messages about this: https://github.com/ksheumaker/homeassistant-apsystems_ecur/issues?q=is%3Aissue+is%3Aclosed+ecu+using+cached+data 
Is more an ECU placement issue than it is an integration issue.

**Comment by m3tc0n** [comment]
Thanks for your response. My ECU has been in the same place as long as I have it. It used to work fine, but lately I have this problem.

**Comment by HAEdwin** [comment]
Look for environmental changes you made since the cache errors occured. Have you added an extra AP, Zigbee devices? Does it help when you position the ECU somewhere else?

**Comment by m3tc0n** [comment]
I didn't make any environmental changes. I now have replaced my ECU to the attic, but that makes no difference.

**Comment by HAEdwin** [comment]
Great! Thanks for the feedback, I'll close the issue. Feel free to open a new one if needed.
