### ISSUE TITLE
Frozen data

### ISSUE THREAD

**Issue by rlucas1** [ksheumaker/homeassistant-apsystems_ecur#277]
Since a few weeks, integration get only one value from ECU, and after stay on this value. When I restart HA, I get the new value, and stay on this value. Query device is on.

in following screenshot, the change occurs after HA restart :

<img width="552" alt="Screenshot 2024-11-19 at 14 46 28" src="https://github.com/user-attachments/assets/84819425-c449-426a-a287-757db58c4544">

Bug seems to have started on 14th november.

Configuration is ok.
Integration version : v1.4.3
ECU-R : 
- firmware : 1.3.15
- ID : 2160

Home Assistant : 
- version :  2024.11.2
- server : raspberry pi

**Comment by HAEdwin** [comment]
That's weird. One approach would be to enable debug logging and see if what's happening (or not) at a five minute interval. You might want to try to reapply the settings. Another approach would be to delete the integration settings (Settings > Devices & services) select the integration and the overflow menu (right of the "Configuration") and choose Delete. What this does is delete only the settings. Reboot HA and add the integration again. This should bring back all entities. If they show up in the integration but don't show up in UI, there might have been another instance of the entities from previously installation(s) i.e. sensor.ecu_current_power_1 or something like that. Correct them manually. Hope the SD card is not corrupt.

**Comment by rlucas1** [comment]
It works I had to delete integration and install it again. Any clue about why these had happened ?
