### ISSUE TITLE
Add plugin to HACS

### ISSUE THREAD

**Issue by ksheumaker** [ksheumaker/homeassistant-apsystems_ecur#4]
Investigate how HACS works, and get this integration included as part of HACS to make it easier to install and update for end users.

**Comment by willemstoker** [comment]
Why not make it a usual integration in Home Assistant?

**Comment by bgbraga** [comment]
Please, if you could change this integration folders we could add it as extra repository at HACS.

The structure should be something like:
custom_components/apsystems_ecur/__init_.py
custom_components/apsystems_ecur/sensor.py
custom_components/apsystems_ecur/manifest.json
info.md
README.md

https://hacs.xyz/docs/publish/integration/

**Comment by ksheumaker** [comment]
@bgbraga Ok, this should be easy enough - i'll get an update done tonight to move everything

**Comment by ksheumaker** [comment]
Directory structure changed, will work with HACS now.
