### ISSUE TITLE
HA Release 2022.4 causes sensors to fail

### ISSUE THREAD

**Issue by HAEdwin** [ksheumaker/homeassistant-apsystems_ecur#62]
sensor.py needs to be modified (no time to create pull request at this moment, this is my reminder here)
Add the following line: 
`from homeassistant.helpers.entity import EntityCategory`
Replace: 
`entity_category="diagnostic"` 
for 
`entity_category=EntityCategory.DIAGNOSTIC`

switch.py and binairy_sensor.py also fixed in my repository. If no comments are made on this fix I'll close this issue.

**Comment by otello86** [comment]
Hello
i do the update on sensor.py, it solved some problems but ECU_querying is still unavailable.
I already have this error in logs : 

Logger: homeassistant.components.switch
Source: helpers/entity_registry.py:529
Integration: Commutateur (documentation, issues)
First occurred: 08:43:44 (2 occurrences)
Last logged: 08:43:45

Error adding entities for domain switch with platform apsystems_ecur
Error while setting up apsystems_ecur platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

**Comment by Scholtz-i** [comment]
I have made all the changes from HAEdwin (Pull requests => File changed) and it works perfectly again.
Big thanks to HAEdwin.

**Comment by otello86** [comment]
Yes i saw, thanks

**Comment by HAEdwin** [comment]
For a quick reference I'll post the changes:
sensor.py
![image](https://user-images.githubusercontent.com/82239374/162617574-b6b446af-8854-4c35-a4fc-2711c95a1277.png)

binary_sensor.py
![image](https://user-images.githubusercontent.com/82239374/162617591-da482293-9946-405f-b24a-750d22646e8d.png)

switch.py
![image](https://user-images.githubusercontent.com/82239374/162617604-dd9d0113-8529-4761-a6a4-1094d95f423c.png)

**Comment by ksheumaker** [comment]
Compatibility with 2022.4 fixed in release v1.2.12
