### ISSUE TITLE
Cannot "Add Integration" after adding repository

### ISSUE THREAD

**Issue by clandmeter** [ksheumaker/homeassistant-apsystems_ecur#64]
Not sure im doing something wrong here, but when I add the repository in HACS as described in the readme via custom repositories, it does not show when I visit Configuration -> Devices/Services -> Integrations -> Add Integrations. Typing apsystems does not show anything.

I am running: Home Assistant 2022.4.1

**Comment by HAEdwin** [comment]
After adding via HACS you have to restart HA.

**Comment by clandmeter** [comment]
Yup did that, still doesnt list it, it was red color before the restart

![image](https://user-images.githubusercontent.com/52970/162535185-7b008168-669a-4fd0-94c1-097daa350a39.png)

When searching for apsystems it does not show anything:

![image](https://user-images.githubusercontent.com/52970/162535352-293d01d9-4050-4e18-967e-e11e2213911a.png)

**Comment by HAEdwin** [comment]
It might have to do with incompatibility (issue #09) Try to correct the 3 files using these directives https://gathering.tweakers.net/forum/insert_bookmark/2032302/71191574 then restart HA and try to add/find it again.

**Comment by clandmeter** [comment]
The #9 PR is a year old, are you sure that's the related PR?
I did try your branch at https://github.com/HAEdwin/homeassistant-apsystems_ecur
But that didn't make a difference.

I was expecting to find some error in the log, but I don't see anything related.

**Comment by clandmeter** [comment]
Ok I found the issue, I needed to clear my browsers cache and the integration popped up.

**Comment by HAEdwin** [comment]
I was referring to the wrong issue #9 but I meant to refer to issue #63. Great that you've found the solution.
