### ISSUE TITLE
ECU-B with DS3-S

### ISSUE THREAD

**Issue by GeorgWolter** [ksheumaker/homeassistant-apsystems_ecur#87]
Installation with HACS was successful.
But the Integration dialogue under Settings -> Devices & Services can't find "APSystems PV Solar ECU".

core-2022.7.6

**Comment by HAEdwin** [comment]
You should be able to find it by only typing: APS 
Have you restarted HA after installation with HACS? There could be a caching issue.

**Comment by GeorgWolter** [comment]
So today the installation process worked fine!
Thank you!

**Comment by HAEdwin** [comment]
Great, thank you for the feedback - you should be able to close this issue now because I can't moderate this.

**Comment by GeorgWolter** [comment]
Closed
